### ISSUE TITLE
GET /stats/

### ISSUE THREAD

**Issue by sebastienrichoz** [damienrochat/TWEB-Interactive-Polls#1]
Récupérer les 3 stats pour la landing page (total sur tous les poll existants)

![image](https://cloud.githubusercontent.com/assets/5737238/21964676/ce8f0588-db50-11e6-9055-1513d2cbccab.png)

**Comment by dmnrcht** [comment]
GET /api/v1/statistics/
{
  "nb_pollrooms": 1,
  "nb_questions": 1,
  "nb_answers": 3
}
